CREATE TABLE COACHES(
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FAMILY_NAME TEXT NOT NULL,
	FIRST_NAME TEXT NOT NULL,
	SECOND_NAME TEXT NOT NULL
);

INSERT INTO COACHES VALUES(NULL, "Терехов", "Евгений", "Александрович");
INSERT INTO COACHES VALUES(NULL, "Марченко", "Валентин", "Евгеньевич");

CREATE TABLE SPORTS(
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	SPORT_NAME TEXT NOT NULL
);

INSERT INTO SPORTS VALUES(NULL, "Баскетбол");
INSERT INTO SPORTS VALUES(NULL, "Волейбол");
INSERT INTO SPORTS VALUES(NULL, "Лыжи");
INSERT INTO SPORTS VALUES(NULL, "Бокс");
INSERT INTO SPORTS VALUES(NULL, "Футбол");

CREATE TABLE SCHOOLS(
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	SCHOOL_NAME TEXT NOT NULL
);

INSERT INTO SCHOOLS VALUES(NULL, "МБОУ СОШ №2");
INSERT INTO SCHOOLS VALUES(NULL, "МБОУ СОШ №1");

CREATE TABLE CLASSES(
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	CLASS_NAME TEXT NOT NULL
);

INSERT INTO CLASSES VALUES(NULL, "5А");
INSERT INTO CLASSES VALUES(NULL, "5Б");
INSERT INTO CLASSES VALUES(NULL, "6А");
INSERT INTO CLASSES VALUES(NULL, "6Б");
INSERT INTO CLASSES VALUES(NULL, "7А");
INSERT INTO CLASSES VALUES(NULL, "7Б");

CREATE TABLE GENDERS(
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	GENDER TEXT NOT NULL
);

INSERT INTO GENDERS VALUES(NULL, "М");
INSERT INTO GENDERS VALUES(NULL, "Ж");

CREATE TABLE STAGES(
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	STAGE_NAME TEXT NOT NULL
);

INSERT INTO STAGES VALUES(NULL, "НП-1");
INSERT INTO STAGES VALUES(NULL, "НП-2");
INSERT INTO STAGES VALUES(NULL, "ТГ-1");
INSERT INTO STAGES VALUES(NULL, "ТГ-2");

CREATE TABLE STUDENTS(
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FAMILY_NAME TEXT NOT NULL,
	FIRST_NAME TEXT NOT NULL,
	SECOND_NAME TEXT NOT NULL,
	GENDER_ID INTEGER NOT NULL REFERENCES GENDERS(ID),
	SCHOOL_ID INTEGER NOT NULL REFERENCES SCHOOLS(ID),
	CLASS_ID INTEGER NOT NULL REFERENCES CLASSES(ID),
	SPORT_ID INTEGER NOT NULL REFERENCES SPORTS(ID),
	COACH_ID INTEGER NOT NULL REFERENCES COACHES(ID),
	STAGE_ID INTEGER NOT NULL REFERENCES STAGES(ID)
);

INSERT INTO STUDENTS VALUES(NULL, "Терехов", "Михаил", "Евгеньевич", 1, 1, 1, 1, 1, 1);
INSERT INTO STUDENTS VALUES(NULL, "Кто-тов", "Кто-то", "Кто-товичы", 1, 1, 1, 1, 1, 1);
